### PR TITLE
schema: common: Move from Movestatus enum to String

### PR DESCRIPTION
**Pull request by patrickelectric**
yaserde enum is not working

Signed-off-by: Patrick José Pereira <patrickelectric@gmail.com>

### CODE REVIEW

**Comment by patrickelectric** [comment]
Master code fails to decode the following XML, and that's what this PR fix:
```
<?xml version="1.0" encoding="UTF-8"?>
<tptz:GetStatusResponse
	xmlns:e="http://www.w3.org/2003/05/soap-encoding"
	xmlns:hikwsd="http://www.onvifext.com/onvif/ext/ver10/wsdl"
	xmlns:hikxsd="http://www.onvifext.com/onvif/ext/ver10/schema"
	xmlns:s="http://www.w3.org/2003/05/soap-envelope"
	xmlns:tan="http://www.onvif.org/ver20/analytics/wsdl"
	xmlns:tds="http://www.onvif.org/ver10/device/wsdl"
	xmlns:ter="http://www.onvif.org/ver10/error"
	xmlns:tev="http://www.onvif.org/ver10/events/wsdl"
	xmlns:timg="http://www.onvif.org/ver20/imaging/wsdl"
	xmlns:tmd="http://www.onvif.org/ver10/deviceIO/wsdl"
	xmlns:tns1="http://www.onvif.org/ver10/topics"
	xmlns:tptz="http://www.onvif.org/ver20/ptz/wsdl"
	xmlns:tr2="http://www.onvif.org/ver20/media/wsdl"
	xmlns:trt="http://www.onvif.org/ver10/media/wsdl"
	xmlns:tt="http://www.onvif.org/ver10/schema"
	xmlns:wsa="http://www.w3.org/2005/08/addressing"
	xmlns:wsnt="http://docs.oasis-open.org/wsn/b-2"
	xmlns:wstop="http://docs.oasis-open.org/wsn/t-1"
	xmlns:xmime="http://www.w3.org/2005/05/xmlmime"
	xmlns:xop="http://www.w3.org/2004/08/xop/include"
	xmlns:xs="http://www.w3.org/2001/XMLSchema"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<tptz:PTZStatus>
		<tt:Position>
			<tt:PanTilt space="http://www.onvif.org/ver10/tptz/PanTiltSpaces/PositionGenericSpace" x="0.0" y="0.0" />
			<tt:Zoom x="0.0" space="http://www.onvif.org/ver10/tptz/ZoomSpaces/PositionGenericSpace" />
		</tt:Position>
		<tt:MoveStatus>
			<tt:PanTilt>IDLE</tt:PanTilt>
			<tt:Zoom>IDLE</tt:Zoom>
		</tt:MoveStatus>
		<tt:UtcTime>2021-03-15T07:45:12Z</tt:UtcTime>
	</tptz:PTZStatus>
</tptz:GetStatusResponse>
```

**Comment by patrickelectric** [comment]
Ping @chrisabruce

**Comment by DmitrySamoylov** [comment]
Why do you think it should be a string? In ONVIF definitions it is clearly a regular enum: https://github.com/lumeohq/onvif-rs/blob/c79d96338f4db7b4b44c70dac4b8d90410b0e551/xsd/common.xsd#L127-L133

**Comment by patrickelectric** [comment]
@DmitrySamoylov I'm not saying that should not be an enum, but that yaserd enum is not work, please check the comment. 
It can't decode it properly, so I moved to string as an easy fix. That can be totally fixed in yaserde, but I don't have time to work with it now.

**Comment by DmitrySamoylov** [comment]
Ah, I see. Please have a look if this helps: https://github.com/lumeohq/onvif-rs/commit/ad67246dc94fba1298259e95e47180df1c6c2898

**Comment by chrisabruce** [comment]
@patrickelectric can you check out master and see if this issue is resolved already?

**Comment by patrickelectric** [comment]
We are going to test today, ping @williangalvani

**Comment by Williangalvani** [comment]
Yes,  that seemed to fix the issue!

**Pull request closed without merging**
